language: android
android:
  components:
    - build-tools-28.0.2
    - android-28

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - ./gradlew install
  - ./gradlew bintrayUpload